{% set version = "1.0.7" %}

package:
  name: msgpack-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/msgpack/msgpack-{{ version }}.tar.gz
  sha256: 572efc93db7a4d27e404501975ca6d2d9775705c2d922390d878fcf768d92c87

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - cython >=0.16
  run:
    - python

test:
  imports:
    - msgpack

about:
  home: http://msgpack.org/
  license: Apache-2.0
  license_file: COPYING
  summary: MessagePack (de)serializer
  license_family: Apache
  dev_url: https://github.com/msgpack/msgpack-python

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - carlodri
