{% set version = "1.1.2" %}

package:
  name: msgpack-python
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/msgpack/msgpack-{{ version }}.tar.gz
  sha256: 3b60763c1373dd60f398488069bcdc703cd08a711477b5d480eecc9f9626f47e

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.11,<3.1.0                 # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - setuptools >=69.5.1
    - cython >=3.0.11,<3.1.0
  run:
    - python

test:
  imports:
    - msgpack
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://msgpack.org/
  license: Apache-2.0
  license_file: COPYING
  summary: MessagePack (de)serializer
  license_family: Apache
  dev_url: https://github.com/msgpack/msgpack-python

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - carlodri
