{% set version = "1.1.0" %}

package:
  name: msgpack-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/msgpack/msgpack-{{ version }}.tar.gz
  sha256: dd432ccc2c72b914e4cb77afce64aab761c1137cc698be3984eee260bcb2896e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython ~=3.0.8                         # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - setuptools
    - cython ~=3.0.8
  run:
    - python

test:
  imports:
    - msgpack

about:
  home: http://msgpack.org/
  license: Apache-2.0
  license_file: COPYING
  summary: MessagePack (de)serializer
  license_family: Apache
  dev_url: https://github.com/msgpack/msgpack-python

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - carlodri
