schema_version: 1

context:
  version: "1.2.3"

package:
  name: msgpack-python
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/msgpack/msgpack-${{ version }}.tar.gz
  sha256: 32edb81a2b5eb7cd7c9d941b2bfbbb082fd2cd09e0e725930316af6b708db186

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython >=3.2.5
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
  host:
    - python
    - pip
    - setuptools >=78.1.1
    - cython >=3.2.5
  run:
    - python

tests:
  - python:
      imports:
        - msgpack
      pip_check: true

about:
  license: Apache-2.0
  license_file: COPYING
  summary: MessagePack (de)serializer
  homepage: http://msgpack.org/
  repository: https://github.com/msgpack/msgpack-python

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - carlodri
