schema_version: 1

context:
  version: "1.2.1"

package:
  name: msgpack-python
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/msgpack/msgpack-${{ version }}.tar.gz
  sha256: 04c721c2c7448767e9e3f2520a475663d8ee0f09c31890f6d2bd70fd636a9647

build:
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: cython >=3.2.5
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
  host:
    - python
    - pip
    - setuptools >=78.1.1
    - cython >=3.2.5
  run:
    - python

tests:
  - python:
      imports:
        - msgpack
      pip_check: true

about:
  license: Apache-2.0
  license_file: COPYING
  summary: MessagePack (de)serializer
  homepage: http://msgpack.org/
  repository: https://github.com/msgpack/msgpack-python

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - carlodri
